### ISSUE TITLE
new design 

### ISSUE THREAD

**Issue by brandonsueur** [importre/alfred-awe#2]
Hello

would be nice to have a dark material Version!

++

**Comment by importre** [comment]
<img width="686" alt="screen shot 2016-07-17 at 1 57 44 pm" src="https://cloud.githubusercontent.com/assets/1744446/16898855/a3aad810-4c26-11e6-8d7e-d0d3de9f2584.png">

depends on your alfred appearance.
how about [this](http://www.packal.org/theme/mapure-dark-material-design)?

**Comment by brandonsueur** [comment]
Very good! I did not see! sorry :relieved:
